
spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3307/myhr?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    clean-disabled: true


server:
  port: ${SERVER_PORT:8080}
  error:
    include-stacktrace: always
    include-message: always


app:
  jwt:
    secret: ${APP_JWT_SECRET:change-this-in-dev-only-please}  
    issuer: myhr
    expires-min: 30
    refresh-exp-days: 7


recaptcha:
  site: ${RECAPTCHA_SITE_KEY:}
  secret: ${RECAPTCHA_SECRET_KEY:}
  minScore: ${RECAPTCHA_MIN_SCORE:0.5}

logging:
  level:
    root: INFO
    org.springframework: DEBUG
    org.hibernate.SQL: DEBUG
    com.myhr: DEBUG
