spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true

    locations: classpath:db/migration


server:
  port: ${SERVER_PORT:8080}

app:
  base-url: ${APP_BASE_URL}

recaptcha:
  site: ${RECAPTCHA_SITE_KEY}
  secret: ${RECAPTCHA_SECRET_KEY}
  minScore: ${RECAPTCHA_MIN_SCORE:0.5}

logging:
  level:
    root: INFO
