app:
  mail:
    enabled: true

spring:
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    check-template-location: true


  profiles:
    active: dev
